{"name": "testFour", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def testFour():\n        print(\"I am method four\")\n>       assert False\nE       assert False\n\ntest_allure.py:19: AssertionError"}, "start": 1671363438962, "stop": 1671363438962, "uuid": "2e6a3ebb-6353-4e8b-9303-c17bd8585040", "historyId": "26384c762c73eaa647d396a20cd99394", "testCaseId": "6f817e9cdb6db20ce56e9ab1d77a2236", "fullName": "test_allure#testFour", "labels": [{"name": "suite", "value": "test_allure"}, {"name": "host", "value": "NahidNiloy14"}, {"name": "thread", "value": "10936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}